### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by VerteXGMD** [julelang/jule#17]
### What would you like to share?

YOU HAVE STOLEN THE CODE FROM GO COMPILER STD!!! BRUH YOU ARE BAD! 👹

**Comment by mertcandav** [comment]
Hi,
Yes, some code in the standard library is adapted from the Go's standard library.
The license references in this regard have not been adequately fulfilled.
We regret that it was not clearly fulfilled in a timely manner.

The necessary conditions have been fulfilled in the relevant places in the code.
Thanks for your contribution.
